name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  CONTAINER_APP_NAME: hemoglobinopathy-analysis
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  CONTAINER_APP_CONTAINER_NAME: hemoglobinopathy-analysis

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image
      run: |
        docker build -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }} .
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}

    - name: Update Container App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }} \
            --set-env-vars \
              OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} \
              TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} \
              TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }} \
              DEPLOY_WHATSAPP_SERVER=true
